[package]
name = "trad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ratatui = "*"
tui-input = "*"
crossterm = "0.26"
crossbeam-channel = "0.4.2"
structopt = "0.3"
